import { cookies } from "next/headers"
import { db } from "@/lib/db"
import { getAppDate } from "@/lib/app-date"
import { generateSalariesForMonth } from "@/lib/generate-salaries"
import { getCurrentPeriod, isIpcAlertPeriod } from "@/lib/salary"

const PAYROLL_SKIP_AUTO_COOKIE = "payroll-skip-auto"

export type PayrollStatus = {
  month: number
  year: number
  hasIpc: boolean
  ipcPercentage: number | null
  showIpcPrompt: boolean
  isIpcUrgentPeriod: boolean
  hasIpcAdjustedEmployees: boolean
  eligibleEmployeeCount: number
  missingSalaryCount: number
  canGenerateSalaries: boolean
  salariesAutoGenerated: boolean
}

async function computePayrollStatus(appDate?: Date): Promise<PayrollStatus> {
  const date = appDate ?? (await getAppDate())
  const { month, year } = getCurrentPeriod(date)

  const monthlyIpc = await db.monthlyIpc.findUnique({
    where: { month_year: { month, year } },
  })
  const hasIpc = Boolean(monthlyIpc)
  const ipcPercentage = monthlyIpc ? Number(monthlyIpc.percentage) : null

  const activeUsers = await db.user.findMany({
    where: { active: true },
    select: {
      id: true,
      ipcAdjusted: true,
      baseSalary: true,
      _count: { select: { salaries: true } },
    },
  })

  const eligibleEmployees = activeUsers.filter(
    (u) => u.ipcAdjusted || u.baseSalary != null || u._count.salaries > 0,
  )

  const hasIpcAdjustedEmployees = eligibleEmployees.some((e) => e.ipcAdjusted)

  const existingSalaries = await db.salary.findMany({
    where: {
      month,
      year,
      userId: { in: eligibleEmployees.map((e) => e.id) },
    },
    select: { userId: true },
  })

  const withSalary = new Set(existingSalaries.map((s) => s.userId))
  const missingSalaryCount = eligibleEmployees.filter((e) => !withSalary.has(e.id)).length

  const isIpcUrgentPeriod = isIpcAlertPeriod(date)
  const showIpcPrompt = !hasIpc

  const canGenerateSalaries =
    missingSalaryCount > 0 && (!hasIpcAdjustedEmployees || hasIpc)

  return {
    month,
    year,
    hasIpc,
    ipcPercentage,
    showIpcPrompt,
    isIpcUrgentPeriod,
    hasIpcAdjustedEmployees,
    eligibleEmployeeCount: eligibleEmployees.length,
    missingSalaryCount,
    canGenerateSalaries,
    salariesAutoGenerated: false,
  }
}

/** Lee el estado del mes y genera liquidaciones si el IPC ya está cargado. */
export async function syncPayrollForCurrentPeriod(appDate?: Date): Promise<PayrollStatus> {
  const status = await computePayrollStatus(appDate)

  if (!status.canGenerateSalaries) return status

  const cookieStore = await cookies()
  const skipKey = `${status.month}-${status.year}`
  if (cookieStore.get(PAYROLL_SKIP_AUTO_COOKIE)?.value === skipKey) {
    return status
  }

  await generateSalariesForMonth(status.month, status.year)

  const updated = await computePayrollStatus(appDate)
  return { ...updated, salariesAutoGenerated: true }
}

export async function getPayrollStatus(appDate?: Date): Promise<PayrollStatus> {
  return computePayrollStatus(appDate)
}
